version: 2.1

install_hex_rebar: &install_hex_rebar
  run:
    name: Install hex and rebar
    command: |
      mix local.hex --force
      mix local.rebar --force

jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/elixir:1.13.1
        environment:
          MIX_ENV: test
      - image: circleci/postgres:11.14
        environment:
          POSTGRES_DB: chess_test
          POSTGRES_HOST: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

    working_directory: ~/app

    steps:
      - checkout
      - <<: *install_hex_rebar
      - restore_cache:
          keys:
            - v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v1-mix-cache-{{ .Branch }}
            - v1-mix-cache
      - restore_cache:
          keys:
            - v1-build-cache-{{ .Branch }}
            - v1-build-cache
      - run: mix do deps.get, compile
      - run: MIX_ENV=dev mix do deps.get, compile

      - run: echo "$OTP_VERSION $ELIXIR_VERSION" > .version_file
      - restore_cache:
          keys:
            - v1-plt-cache-{{ checksum ".version_file" }}-{{ checksum "mix.lock" }}
      - run: MIX_ENV=dev mix dialyzer --plt
      - save_cache:
          key: v1-plt-cache-{{ checksum ".version_file"  }}-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps
            - ~/.mix
            - priv/plts

      - save_cache:
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths:
            - deps
      - save_cache:
          key: v1-build-cache-{{ .Branch }}
          paths:
            - _build

      - persist_to_workspace:
          root: .
          paths:
            - .

  compile-warnings:
    parallelism: 1
    docker:
      - image: circleci/elixir:1.13.1

    working_directory: ~/app

    steps:
      - attach_workspace:
          at: .
      - <<: *install_hex_rebar
      - run:
          name: Compile Checks
          command: mix compile --warnings-as-errors

  test:
    docker:
      - image: circleci/elixir:1.13.1
        environment:
          MIX_ENV: test
      - image: circleci/postgres:11.14
        environment:
          POSTGRES_DB: chess_test
          POSTGRES_HOST: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

    working_directory: ~/app

    steps:
      - attach_workspace:
          at: .
      - <<: *install_hex_rebar
      - run:
          name: Mix Test
          command: mix test
      - store_artifacts:
          path: cover
          destination: coverage_results
      - store_test_results:
          path: _build/test/junit

  format:
    docker:
      - image: circleci/elixir:1.13.1
    working_directory: ~/app

    steps:
      - attach_workspace:
          at: .
      - <<: *install_hex_rebar
      - run:
          name: Mix Format
          command: mix format --check-formatted

  credo:
    docker:
      - image: circleci/elixir:1.13.1
    working_directory: ~/app

    steps:
      - attach_workspace:
          at: .
      - <<: *install_hex_rebar
      - run:
          name: Mix Credo
          command: mix credo --strict

  dialyzer:
    docker:
      - image: circleci/elixir:1.13.1
        environment:
          MIX_ENV: dev
    working_directory: ~/app

    steps:
      - attach_workspace:
          at: .
      - <<: *install_hex_rebar
      - run: echo "$OTP_VERSION $ELIXIR_VERSION" > .version_file
      - restore_cache:
          keys:
            - v1-plt-cache-{{ checksum ".version_file" }}-{{ checksum "mix.lock" }}
      - run:
          name: Mix Dialyzer
          command: mix dialyzer --no-check

  generate_documentation:
    docker:
      - image: circleci/elixir:1.13.1

    steps:
      - attach_workspace:
          at: .
      - <<: *install_hex_rebar
      - run:
          name: Generate Docs
          command: mix docs
      - store_artifacts:
          path: doc
          destination: documentation

  no_unused_deps:
    docker:
      - image: circleci/elixir:1.13.1

    steps:
      - attach_workspace:
          at: .
      - <<: *install_hex_rebar
      - run:
          name: Check for Unused Deps
          command: mix deps.unlock --check-unused

  security_analysis:
    docker:
      - image: circleci/elixir:1.13.1

    steps:
      - attach_workspace:
          at: .
      - <<: *install_hex_rebar
      - run:
          name: Mix Sobelow
          command: mix sobelow

workflows:
  version: 2
  pipeline:
    jobs:
      - build:
          filters:
            tags:
              only: /^release-.*$/
      - compile-warnings:
          requires:
            - build
          filters:
            tags:
              only: /^release-.*$/
      - no_unused_deps:
          requires:
            - build
          filters:
            tags:
              only: /^release-.*$/
      - test:
          requires:
            - compile-warnings
            - no_unused_deps
          filters:
            tags:
              only: /^release-.*$/
      - format:
          requires:
            - compile-warnings
            - no_unused_deps
      - credo:
          requires:
            - compile-warnings
            - no_unused_deps
      - dialyzer:
          requires:
            - compile-warnings
            - no_unused_deps
          filters:
            tags:
              only: /^release-.*$/
      - security_analysis:
          requires:
            - compile-warnings
            - no_unused_deps
          filters:
            tags:
              only: /^release-.*$/
      - generate_documentation:
          requires:
            - compile-warnings
            - no_unused_deps
