on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
env:
  MIX_ENV: test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/bootstrap_elixir
      - name: Install dependencies
        run: mix deps.get
      - name: Compile
        run: mix compile
  credo-format-sobelow:
    name: Static Analysis, Format Check and Audits
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/bootstrap_elixir
      - name: Run Credo
        run: mix credo --strict
      - name: Check formatted
        run: mix format --check-formatted
      - name: Run Sobelow
        run: mix sobelow --skip
      - name: Run hex audit for retired packages
        run: mix hex.audit
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/bootstrap_elixir
      - name: Run tests
        run: mix test
  dialyzer:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/bootstrap_elixir
      - name: Restore PLT cache
        uses: actions/cache@v4
        id: plt_cache
        with:
          key: ${{ runner.os }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-plt
          restore-keys: ${{ runner.os }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-plt
          path: priv/plts
      - name: Create PLTs
        if: steps.plt_cache.outputs.cache-hit != 'true'
        run: mix dialyzer --plt
      - name: Run dialyzer
        run: mix dialyzer --format github