on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      localWorkspaceFolderBasename: "chess"
    steps:
      - uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        id: deps-cache
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('''**/mix.lock''') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Install dependencies and compile
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            mix deps.get
            mix compile

  lint:
    runs-on: ubuntu-latest
    needs: setup
    env:
      localWorkspaceFolderBasename: "chess"
    steps:
      - uses: actions/checkout@v4

      - name: Restore dependencies
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('''**/mix.lock''') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Run credo and format check
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            mix credo --strict
            mix format --check-formatted

  dialyzer:
    runs-on: ubuntu-latest
    needs: setup
    env:
      localWorkspaceFolderBasename: "chess"
    steps:
      - uses: actions/checkout@v4

      - name: Restore dependencies
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('''**/mix.lock''') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Cache PLT
        uses: actions/cache@v4
        id: plt_cache
        with:
          path: priv/plts
          key: ${{ runner.os }}-plt-${{ hashFiles('''**/mix.lock''') }}
          restore-keys: |
            ${{ runner.os }}-plt-

      - name: Run dialyzer
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            if [ "${{ steps.plt_cache.outputs.cache-hit }}" != 'true' ]; then
              mix dialyzer --plt --plt-path priv/plts
            fi
            mix dialyzer --format github --plt-path priv/plts

  test:
    runs-on: ubuntu-latest
    needs: setup
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v4

      - name: Restore dependencies
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('''**/mix.lock''') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Run tests
        uses: devcontainers/ci@v0.3
        with:
          runCmd: mix test